# Generated by Django 6.0.1 on 2026-01-20 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('title_zh', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('excerpt_zh', models.TextField()),
                ('excerpt_en', models.TextField()),
                ('content_zh', models.TextField()),
                ('content_en', models.TextField()),
                ('cover_image', models.ImageField(upload_to='blog/covers/')),
                ('seo_title_zh', models.CharField(blank=True, max_length=200)),
                ('seo_title_en', models.CharField(blank=True, max_length=200)),
                ('seo_description_zh', models.CharField(blank=True, max_length=300)),
                ('seo_description_en', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('read_time_minutes', models.PositiveIntegerField(default=1)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_posts', models.ManyToManyField(blank=True, to='Eurowinetrip.blogpost')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Eurowinetrip.category')),
                ('tags', models.ManyToManyField(blank=True, to='Eurowinetrip.tag')),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Eurowinetrip.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Eurowinetrip.blogpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
