# Generated by Django 6.0.1 on 2026-01-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eurowinetrip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
