# Generated by Django 5.2.6 on 2026-01-27 15:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eurowinetrip', '0004_alter_blogpost_id_alter_category_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_zh',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
