# Generated by Django 6.0.1 on 2026-02-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eurowinetrip', '0009_alter_comment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='geo_icbm',
            field=models.CharField(blank=True, help_text='Exact coordinates: Latitude, Longitude (e.g., 50.0515, 7.1186)', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='geo_placename',
            field=models.CharField(blank=True, help_text='Specific location name for the search engine map', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='geo_region',
            field=models.CharField(blank=True, help_text='ISO 3166-2 region code (e.g., DE-RP for Mosel, FR-NAQ for Bordeaux)', max_length=10),
        ),
    ]
