# Generated by Django 6.0.1 on 2026-02-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eurowinetrip', '0010_blogpost_geo_icbm_blogpost_geo_placename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='ai_summary_en',
            field=models.TextField(blank=True, help_text='Fact-based summary for Google Gemini to cite.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='ai_summary_zh',
            field=models.TextField(blank=True, help_text='Fact-based summary for Baidu Ernie Bot to cite.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_alt_en',
            field=models.CharField(blank=True, help_text='AI SEO: Description of the cover photo for Google SGE', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_alt_zh',
            field=models.CharField(blank=True, help_text='AI SEO: Description of the cover photo for Baidu Ernie', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='key_entities',
            field=models.CharField(blank=True, help_text='Comma-separated list of entities (Region, Grape, Vintage) for AI reasoning.', max_length=500),
        ),
        migrations.AddField(
            model_name='postimage',
            name='alt_text_en',
            field=models.CharField(blank=True, help_text='Describe image for English AI agents', max_length=200),
        ),
        migrations.AddField(
            model_name='postimage',
            name='alt_text_zh',
            field=models.CharField(blank=True, help_text='Describe image for Chinese AI agents', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='geo_icbm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='geo_placename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='geo_region',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
