# Generated by Django 6.0.1 on 2026-02-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eurowinetrip', '0011_blogpost_ai_summary_en_blogpost_ai_summary_zh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='Mandatory: Check if the cover image or main content is AI-generated.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_ai_polished',
            field=models.BooleanField(default=False, help_text='Best Practice: Check if human-written but AI-polished or translated.'),
        ),
    ]
