# Generated by Django 6.0.1 on 2026-02-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eurowinetrip', '0012_blogpost_is_ai_generated_blogpost_is_ai_polished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='is_ai_generated',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='is_ai_polished',
        ),
    ]
